config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations',
    sessions: 'users/sessions' }            
  get "users/show", to: "users#show"
    root 'top#index'

  resources :rooms
  get "/search", to: "rooms#search"

  resources :reservations, only: [:new, :index, :create, :show] do
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :room_image, RoomImageUploader

  validates :room_name, presence: true
  validates :room_introduction, presence: true
  validates :fee, presence: true, numericality: true
  validates :address, presence: true
  validates :room_image, presence: true

  belongs_to :user
  has_many :reservations
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new
  end

  def create
    room = Room.new(room_params.merge(user_id: current_user.id))
    if room.save!
      redirect_to rooms_path, notice:"新しいルームを登録しました。"
    else
      render new
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def search
    if params[:search_area].present?
      @rooms = Room.where('rooms.address LIKE(?)', "%#{params[:search_area]}%")
    elsif params[:search_keyword].present?
      @rooms = Room.where('rooms.address LIKE(?) OR rooms.room_name LIKE(?) OR rooms.room_introduction LIKE(?)', 
      "%#{params[:search_keyword]}%", "%#{params[:search_keyword]}%", "%#{params[:search_keyword]}%")  
    else
      @rooms = Room.none
    end  
  end

  private

    def room_params
      params.require(:room).permit(:room_name, :room_introduction, :fee, :address, :room_image)
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="room_index_page m-5">

  <div class="room_index_header">
    <h5>登録済みルーム一覧</h5>
  </div>

  <div class="room_index_body">
  <table class="table">
    <tr class="index-table-title">
      <th class="index-title">ルーム画像</th>
      <th class="index-title">ルーム名</th>
      <th class="index-title">ルーム紹介</th>
      <th class="index-title">料金</th>
      <th class="index-title">作成日</th>
    </tr>

    <% @rooms.each do |room| %>
    <tr class="index-table-body">
        <td class="index-body">
          <a class="room-image"><%= link_to image_tag(room.room_image.url), room_path(room.id) %></a>
        </td>
        <td class="index-body"><%= link_to room.room_name, room_path(room.id) %></td>
        <td class="index-body"><%= room.room_introduction %></td>
        <td class="index-body">¥<%= room.fee %></td>
        <td class="index-body"><%= room.created_at %></td>
    </tr>
    <% end %>
  </table>
  </div>

</div>

app/views/rooms/new.html.erb
<div class="registration_for_room">
      <div class = "roomHeader mt-5">
        <p class="room-content">ルーム情報登録</p>
      </div>
    
        <%= form_with model:@room, local:true do |f| %>
        <%= hidden_field_tag :id, @room.id %>

        <table class="table room-registration-table">
          <div class = "form-group col-xs-4 room-content">
          <tr>
            <th><label>ルーム名 <span class = "must">必須</span></label></th>
            <td><%= f.text_field :room_name, class: "form-control new_form", placeholder:"ルーム名を入力" %></td>
          </tr>
          </div>
    
          <div class="form-group col-xs-4 room-content">
          <tr>
            <th><label>ルーム紹介 <span class = "must">必須</span></label></th>
            <td><%= f.text_area :room_introduction, class: "form-control new_form", placeholder: "ルーム説明を入力"%></td>
          </tr>
          </div>
        
          <div class="form-group col-xs-4 room-content">
          <tr>
            <th><label>料金 <span class = "must">必須</span></label></th>
            <td><%= f.text_field :fee, class: "form-control new_form", placeholder: "一日あたりの料金を入力" %></td>
          </tr>
          </div>
        
          <div class="form-group col-xs-4 room-content">
          <tr>
            <th>住所 <label><span class = "must">必須</span></label></th>
            <td><%= f.text_field :address, class: "form-control new_form", placeholder: "住所を入力" %></td>
          </tr>
    
          <div class="form-group col-xs-4 room-content">
          <tr>
            <th>ルーム画像 <label><span class = "must">必須</span></label></th>
            <td><%= f.file_field :room_image %></td>
          </tr>
    
          </div>
        </table>
    
        <div class="making_room_button">
          <%= f.submit "登録", class: "btn btn-primary making_room"%>
        </div>
    
        <% end %>
      </div>
      </div>
    </div>
</div>

app/views/rooms/search.html.erb
<div class="room_search_page m-5">

<div class="room_search_header">
    <h5>検索結果 : <%= @rooms.count %>件</h5>
</div>

<div class="room_search_table">
<table class="table">

    <tr class="search-table-title">
        <th class="search-title">ルーム画像</th>
        <th class="search-title">ルーム名</th>
        <th class="search-title">住所</th>
        <th class="search-title">ルーム紹介</th>
        <th class="search-title">料金</th>
    </tr>

    <% @rooms.each do |room| %>
    <tr class="search-table-body">
        <td class="search-body">
            <a class="room-image"><%= link_to image_tag(room.room_image.url), room_path(room.id) %></a>
        </td>
        <td class="search-body"><%= link_to room.room_name, room_path(room.id) %></td>
        <td class="search-body"><%= room.address %></td>
        <td class="search-body"><%= room.room_introduction %></td>
        <td class="search-body">¥<%= room.fee %></td>
    </tr>
    <% end %>

</table>
</div>

</div>

app/views/rooms/show.html.erb
<div class="new_reservation_page container m-5">
  <div class = "row">

    <div class="col-lg-8 col-md-12 col-sm-12">
    <div class="show-detail">
      <div class="big-room-picture">
        <%= image_tag(@room.room_image.url(:thumb)) %>
      </div>

      <table class="room-detail-table">
        <tr>
          <th>
            <div class="owner-icon">
              <a href= "/">
                <img class="icon-itself" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon.jpg">
              </a>
            </div>
          </th>
          <td>
            <div class="room_area_detail">
              <p class="show_room_name"><%= @room.room_name %></p>
              <p class="show_room_adress"><%= @room.address %></p>
            </div>
          </td>
        </tr>

        <tr>
        <td>
          <div class="show_room_intro">
            <p class="show_room_main"><%= @room.room_introduction %></p>
          </div>
        </td>
        </tr>
      </table>
    
    </div>
    </div>


    <div class="col-lg-4 col-md-12 col-sm-12">
      <div class="reservation_system_bar">

        <p class="show_price">¥ <%= @room.fee %> / 日</p>

        <%= form_with model:@reservation, url: new_reservation_path, method: :get do |f| %>  
        
          <%= f.label :start, "開始日" %>
          <%= f.date_field :start, class: "form-control", placeholder:"年/月/日" %>  
          <%= f.label:end_date, "終了日" %>
          <%= f.date_field :end_date, class: "form-control", placeholder:"年/月/日" %>  
          <%= f.label:guests, "人数" %>
          <%= f.number_field :guests, class: "form-control" %>
          
          <%= hidden_field_tag :id, @room.id %>

          <div class="reserve_room">
            <%= f.submit "予約する", class: "btn btn-primary btn-block reserve_room_button"%>
          </div>

        <% end %>

      </div>
    </div>
  
  </div>
</div>